# Generated by Django 5.0.3 on 2024-03-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
