# Generated by Django 5.0.3 on 2024-03-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_students_crud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crud',
        ),
    ]
